### ISSUE TITLE
Fails when project created in VS2013 opened in VS2015

### ISSUE THREAD

**Issue by miksh7** [bennor/AutoT4MVC#16]
I've got T4MVC 1.5.2 working fine under VS2013 Update5. When open the same project in VS2015 the template build fails with:

System.Exception was unhandled by user code
  HResult=-2146233088
  Message=Template runtime error
  Source=acomtdlz
  StackTrace:
       at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.TransformText() in d:\Projects\MyProject\T4MVC.tt:line 423
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()
  InnerException: 
       ErrorCode=-2147467259
       HResult=-2147467259
       Message=Error HRESULT E_FAIL has been returned from a call to a COM component.
       Source=mscorlib
       StackTrace:
            at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
            at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.ExternalCodeFunction.get_FunctionKind()
            at EnvDTE80.CodeFunction2.get_FunctionKind()
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ResultTypeInfo.<.ctor>b__65(CodeFunction2 f) in d:\Projects\MyProject\T4MVC.tt:line 1893
            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
            at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
            at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ResultTypeInfo..ctor(CodeTypeRef codeType) in d:\Projects\MyProject\T4MVC.tt:line 1892
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ProcessControllerActionMethods(ControllerInfo controllerInfo, CodeClass2 current) in d:\Projects\MyProject\T4MVC.tt:line 881
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ProcessControllerType(CodeClass2 type, AreaInfo area, DateTime controllerLastWriteTime) in d:\Projects\MyProject\T4MVC.tt:line 759
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in d:\Projects\MyProject\T4MVC.tt:line 691
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in d:\Projects\MyProject\T4MVC.tt:line 676
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ProcessAreaControllers(ProjectItems areaFolderItems, AreaInfo area, ProjectItem areaFolder) in d:\Projects\MyProject\T4MVC.tt:line 646
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.ProcessProjectRoot(Project project) in d:\Projects\MyProject\T4MVC.tt:line 569
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.PrepareDataToRender(TextTransformation tt) in d:\Projects\MyProject\T4MVC.tt:line 545
            at Microsoft.VisualStudio.TextTemplating8E8910B59E682CB5902E2DC58F73F722279256FD52EE5A921B3A8A64F8534B2369443515B9A41B29A3B9E1BF4FF88AB1A03EF0EA83A8EB7204C181097889082D.GeneratedTextTransformation.TransformText() in d:\Projects\MyProject\T4MVC.tt:line 40
       InnerException:

**Comment by miksh7** [comment]
Sorry, that should be moved to T4MVC project
